### ISSUE TITLE
Typos in zshrc

### ISSUE THREAD

**Issue by chris-negrich** [cnegrich/dotfiles#1]
##### Aliases
alias zshconfig="mate ~/.zshrc"
alias ohmyzsh="mate ~/.oh-my-zsh"
alias home="cd ~"
alias la="echo 'la la la la la' | lolcat -p 1 -a -s 100 && ls -la"
alias c="cd"
alias ..="cd .."
alias ...="cd ../../../"
alias ....="cd ../../../../"
alias o="open ."
alias svi="sudo vi"
alias svim="sudo vim"
alias py="python"
alias gfind="find . | grep"
alias sue="sudo -E"
alias dls="sudo -E docker service ls"
alias dps="sudo -E docker ps"
alias dim="sudo -E docker images"
alias dex="sudo -E docker exec"
alias dlog="docker logs -f"
alias tf="tail -f"
alias lsd="echo 'What a trippy typo...' | lolcat -p 1 -a -s 50 && ls | lolcat -p 1 -a -s 50 -S 10"
alias xclip="xclip -selection c"
alias nao="nano"
alias nanoo="nano"
alias v="sudo vim"
alias run="echo 'Running...' | lolcat -p 1 -a -s 100 -S 10  && make run"

**Comment by cnegrich** [comment]
Changes made.

**Comment by chris-negrich** [comment]
Typo in .zshrc, should be eval "$(ssh-agent -s)", currently is eval "$ssh-agent -s)"
