### ISSUE TITLE
cl Alias

### ISSUE THREAD

**Issue by chris-negrich** [cnegrich/dotfiles#6]
I use this a surprising amount:
alias cl="clear"

**Comment by chris-negrich** [comment]
alias eval="eval '$ssh-agent -s)' && ssh-add ~/.ssh/id_rsa"

**Comment by chris-negrich** [comment]
alias xclip="xclip -selection c" -> alias xcp="xclip -selection c"

**Comment by chris-negrich** [comment]
alias cargobr="cargo build --release"
alias cargotr="cargo test --release -- --nocapture"
alias cargob="cargo build"
alias cargot="cargo test"

**Comment by chris-negrich** [comment]
alias trace_build="RUST_LOG=trace cargo build -v"
alias trace_cargo="RUST_LOG=trace cargo"

**Comment by cnegrich** [comment]
These have all been added.
